### ISSUE TITLE
Demo not displaying Japanese text

### ISSUE THREAD

**Issue by MFukazawa** [mubaidr/vue-swimlane#163]
Is only English language support available?

**Comment by mubaidr** [comment]
Never thought of that! Looks like there are no spaces in-between Japanese words, am I right? 

P.S. This script/plugin splits sentence to words using space. You have a suggestion about this, please share

**Comment by MFukazawa** [comment]
Yes, that's right! Even when adding a space in between words the text wasn't displaying, however.

**Comment by mubaidr** [comment]
It works if spaces are added, please test the following input: 
```
単語 の リ ストを アニメ ーション テキス トスイム レーン とし て表示 しま す。
```

But I don't know to split text for Japanese language. :(

**Comment by MFukazawa** [comment]
Wow, thanks! :)
